import { Inter, Josefin_Sans } from 'next/font/google'
import '@/styles/reset.css'
import '@/styles/global.css'

import Header from '@/Components/header'
import Footer from '@/Components/footer'

const inter = Inter({ subsets: ['latin'] })
const josefin = Josefin_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={josefin.className}>
      <body className='container'>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
